---
title: "SimpleGWAS"
author: "Ryan Christ"
date: "18/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Provide a Working Directory
```{r run.dir, eval=FALSE}
run.dir <- "~/Desktop/autotuning_test_files/"
```


```{r load.data, results = "hide",message=FALSE, eval=FALSE}
require(kalis)
require(RSpectra)
require(mlrMBO)
require(future)
require(pryr)
require(QForm)

require(Matrix)
require(rhdf5)

source("../../AutoTune2_local.R")

data("SmallHaps")
CacheHaplotypes(SmallHaps)
m <- rbeta(nrow(SmallHaps)-1,1,10)*1e-6
pars <- Parameters(CalcRho(morgan.dist = m, Ne = 1e-250, gamma = 1), mu = 1e-250)

polymorphic.sites <- rowSums(SmallHaps)!=0 & rowSums(SmallHaps)!=1
G <- tcrossprod(scale(t(SmallHaps[polymorphic.sites,])))
bg.vecs <- RSpectra::eigs(G,10)$vectors
```


### Load/Simulate Phenotype
```{r c1, eval=FALSE}
set.seed(17)
a <- rbinom(ncol(SmallHaps)/2,1,0.5)
x <- SmallHaps[250,seq(1,ncol(SmallHaps),by=2)] + SmallHaps[250,seq(1,ncol(SmallHaps),by=2)+1]
y <- rbinom(ncol(SmallHaps)/2,size = 1,prob = ifelse(a,1,0.2)*ifelse(x>0,0.8,0.3))
summary(glm(y~a+x,family="binomial"))
```


### Calculate Background Matrices to Adjust for Population Structure

```{r bg.mat.calc, message = F, eval=FALSE}

nthreads <- 2
num.target.loci <- 10
targets <- InvRecombMap(m,num.target.loci = num.target.loci)

cache <- AutoTuneFillForwardCache2(pars, targets, nthreads = 28, fwdtable.dir = run.dir, include.target.snp = F)
start <- proc.time()
global.list <- CalcGlobalDedipsBackwardWithCache(pars, targets, cache, nthreads = 28)
finish <- proc.time() - start

for(i in 1:4){
  class(global.list[[i]]) <- c("kalisDistanceMatrix",class(global.list[[i]]))
}

for(i in 1:4){ plot(global.list[[i]]); browser()}

dedip.bg.vecs <- lapply(global.list[2:4],function(M){cbind(a,eigs(M,20)$vectors)})
rm(global.list); gc()

Ey <- lapply(dedip.bg.vecs,function(X){c(glm(y ~ X,family = "binomial")$fitted.values)})
```



```{r }

```




