---
title: "testing_new_dedip"
author: "Ryan Christ"
date: "21/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Comparing old and new dedip functions.

```{r dedip, eval = FALSE}
require(kalis)
data("SmallHaps")

# Update here by directly writing from R into the cache.
WriteIndividualHaplotypeH5("SmallHaps.h5",SmallHaps)
CacheAllHaplotypes("SmallHaps.h5")
system2("rm","SmallHaps.h5")

set.seed(1432)
m <- rbeta(500-1,1,10)*1e-6

pars <- Parameters(CalcRho(morgan.dist = m, Ne = 1, gamma = 1), mu = 1e-8)
fwd <- MakeForwardTable(pars)
bck <- MakeBackwardTable(pars)

Forward(fwd, pars, 250)
Backward(bck, pars, 250)

d <- DistMat(fwd,bck)
plot(d)
require(Matrix)


tempmat <- fwd$alpha * bck$beta
normalization.constants<-colSums(tempmat)
tempmat<-sweep(x=tempmat,MARGIN = 2,STATS = normalization.constants,FUN = "/")


avail.methods <- c("min","min2nd","dom","max","add","mean")
for(i in 1:6){
  print(all.equal(kalis:::Dedip2(fwd,bck,method=avail.methods[i]),kalis:::Dedip(matrix(1,nrow=nrow(tempmat),ncol=ncol(tempmat)),tempmat,method=avail.methods[i])))
}


dedip.mats <- kalis:::Dedip(matrix(1,nrow=nrow(tempmat),ncol=ncol(tempmat)),tempmat,method="all")
new.dedip.mats <- kalis:::Dedip2(fwd,bck,method="all")
for(i in 1:6) print(all.equal(new.dedip.mats[[i]],dedip.mats[[i]]))

```

