#ifndef EXACTFORWARD_H
#define EXACTFORWARD_H

#include <Rcpp.h>
using namespace Rcpp;

void ExactForward_speidel_cpp(NumericMatrix alpha,
                              NumericVector alpha_f,
                              const int alpha_from_rec,
                              const int alpha_t,
                              const int t,
                              const int from_rec,
                              const int to_rec,
                              const int L,
                              const int N,
                              NumericMatrix Pi,
                              NumericVector mu,
                              NumericVector rho);

void ExactForward_cpp(NumericMatrix alpha,
                      NumericVector alpha_f,
                      const int alpha_from_rec,
                      const int alpha_t,
                      const int t,
                      const int from_rec,
                      const int to_rec,
                      const int L,
                      const int N,
                      NumericMatrix Pi,
                      NumericVector mu,
                      NumericVector rho);

void ParExactForward_speidel_cpp(NumericMatrix alpha,
                                 NumericVector alpha_f,
                                 const int alpha_from_rec,
                                 const int alpha_t,
                                 const int t,
                                 const int from_rec,
                                 const int to_rec,
                                 const int L,
                                 const int N,
                                 NumericMatrix Pi,
                                 NumericVector mu,
                                 NumericVector rho,
                                 const int nthreads);

void ParExactForward_cpp(NumericMatrix alpha,
                         NumericVector alpha_f,
                         const int alpha_from_rec,
                         const int alpha_t,
                         const int t,
                         const int from_rec,
                         const int to_rec,
                         const int L,
                         const int N,
                         NumericMatrix Pi,
                         NumericVector mu,
                         NumericVector rho,
                         const int nthreads);

void ExactForward_speidel_scmu_cpp(NumericMatrix alpha,
                                   NumericVector alpha_f,
                                   const int alpha_from_rec,
                                   const int alpha_t,
                                   const int t,
                                   const int from_rec,
                                   const int to_rec,
                                   const int L,
                                   const int N,
                                   NumericMatrix Pi,
                                   const double mu,
                                   NumericVector rho);

void ExactForward_scmu_cpp(NumericMatrix alpha,
                           NumericVector alpha_f,
                           const int alpha_from_rec,
                           const int alpha_t,
                           const int t,
                           const int from_rec,
                           const int to_rec,
                           const int L,
                           const int N,
                           NumericMatrix Pi,
                           const double mu,
                           NumericVector rho);

void ParExactForward_speidel_scmu_cpp(NumericMatrix alpha,
                                      NumericVector alpha_f,
                                      const int alpha_from_rec,
                                      const int alpha_t,
                                      const int t,
                                      const int from_rec,
                                      const int to_rec,
                                      const int L,
                                      const int N,
                                      NumericMatrix Pi,
                                      const double mu,
                                      NumericVector rho,
                                      const int nthreads);

void ParExactForward_scmu_cpp(NumericMatrix alpha,
                              NumericVector alpha_f,
                              const int alpha_from_rec,
                              const int alpha_t,
                              const int t,
                              const int from_rec,
                              const int to_rec,
                              const int L,
                              const int N,
                              NumericMatrix Pi,
                              const double mu,
                              NumericVector rho,
                              const int nthreads);

void ExactForward_speidel_scPi_cpp(NumericMatrix alpha,
                                   NumericVector alpha_f,
                                   const int alpha_from_rec,
                                   const int alpha_t,
                                   const int t,
                                   const int from_rec,
                                   const int to_rec,
                                   const int L,
                                   const int N,
                                   const double Pi,
                                   NumericVector mu,
                                   NumericVector rho);

void ExactForward_scPi_cpp(NumericMatrix alpha,
                           NumericVector alpha_f,
                           const int alpha_from_rec,
                           const int alpha_t,
                           const int t,
                           const int from_rec,
                           const int to_rec,
                           const int L,
                           const int N,
                           const double Pi,
                           NumericVector mu,
                           NumericVector rho);

void ParExactForward_speidel_scPi_cpp(NumericMatrix alpha,
                                      NumericVector alpha_f,
                                      const int alpha_from_rec,
                                      const int alpha_t,
                                      const int t,
                                      const int from_rec,
                                      const int to_rec,
                                      const int L,
                                      const int N,
                                      const double Pi,
                                      NumericVector mu,
                                      NumericVector rho,
                                      const int nthreads);

void ParExactForward_scPi_cpp(NumericMatrix alpha,
                              NumericVector alpha_f,
                              const int alpha_from_rec,
                              const int alpha_t,
                              const int t,
                              const int from_rec,
                              const int to_rec,
                              const int L,
                              const int N,
                              const double Pi,
                              NumericVector mu,
                              NumericVector rho,
                              const int nthreads);

void ExactForward_speidel_scmuPi_cpp(NumericMatrix alpha,
                                     NumericVector alpha_f,
                                     const int alpha_from_rec,
                                     const int alpha_t,
                                     const int t,
                                     const int from_rec,
                                     const int to_rec,
                                     const int L,
                                     const int N,
                                     const double Pi,
                                     const double mu,
                                     NumericVector rho);

void ExactForward_scmuPi_cpp(NumericMatrix alpha,
                             NumericVector alpha_f,
                             const int alpha_from_rec,
                             const int alpha_t,
                             const int t,
                             const int from_rec,
                             const int to_rec,
                             const int L,
                             const int N,
                             const double Pi,
                             const double mu,
                             NumericVector rho);

void ParExactForward_speidel_scmuPi_cpp(NumericMatrix alpha,
                                        NumericVector alpha_f,
                                        const int alpha_from_rec,
                                        const int alpha_t,
                                        const int t,
                                        const int from_rec,
                                        const int to_rec,
                                        const int L,
                                        const int N,
                                        const double Pi,
                                        const double mu,
                                        NumericVector rho,
                                        const int nthreads);

void ParExactForward_scmuPi_cpp(NumericMatrix alpha,
                                NumericVector alpha_f,
                                const int alpha_from_rec,
                                const int alpha_t,
                                const int t,
                                const int from_rec,
                                const int to_rec,
                                const int L,
                                const int N,
                                const double Pi,
                                const double mu,
                                NumericVector rho,
                                const int nthreads);

void ExactForward1step_speidel_scmuPi_cpp(NumericMatrix alpha,
                                          NumericVector alpha_f,
                                          const int alpha_from_rec,
                                          const int alpha_t,
                                          const int t,
                                          const int from_rec,
                                          const int to_rec,
                                          const int L,
                                          const int N,
                                          const double Pi,
                                          const double mu,
                                          NumericVector rho);

void ExactForward1step_scmuPi_cpp(NumericMatrix alpha,
                                  NumericVector alpha_f,
                                  const int alpha_from_rec,
                                  const int alpha_t,
                                  const int t,
                                  const int from_rec,
                                  const int to_rec,
                                  const int L,
                                  const int N,
                                  const double Pi,
                                  const double mu,
                                  NumericVector rho);

void ParExactForward1step_speidel_scmuPi_cpp(NumericMatrix alpha,
                                             NumericVector alpha_f,
                                             const int alpha_from_rec,
                                             const int alpha_t,
                                             const int t,
                                             const int from_rec,
                                             const int to_rec,
                                             const int L,
                                             const int N,
                                             const double Pi,
                                             const double mu,
                                             NumericVector rho,
                                             const int nthreads);

void ParExactForward1step_scmuPi_cpp(NumericMatrix alpha,
                                     NumericVector alpha_f,
                                     const int alpha_from_rec,
                                     const int alpha_t,
                                     const int t,
                                     const int from_rec,
                                     const int to_rec,
                                     const int L,
                                     const int N,
                                     const double Pi,
                                     const double mu,
                                     NumericVector rho,
                                     const int nthreads);

#endif
