#ifndef EXACTBACKWARD_H
#define EXACTBACKWARD_H

#include <stddef.h>

void ExactBackward_scalarMu_scalarPi(double *const restrict beta,
                                     double *const restrict beta_g,
                                     int *const restrict cur_beta_theta,
                                     int *const restrict end_beta_theta,
                                     const size_t beta_from_rec,
                                     const size_t beta_t,
                                     const size_t t,
                                     const size_t from_rec,
                                     const size_t to_rec,
                                     const size_t L,
                                     const size_t N,
                                     double Pi,
                                     const double mu,
                                     const double *const restrict rho,
                                     const int *const restrict nthreads,
                                     const int nthreads_len);

void ExactBackward_scalarPi(double *const restrict beta,
                            double *const restrict beta_g,
                            int *const restrict cur_beta_theta,
                            int *const restrict end_beta_theta,
                            const size_t beta_from_rec,
                            const size_t beta_t,
                            const size_t t,
                            const size_t from_rec,
                            const size_t to_rec,
                            const size_t L,
                            const size_t N,
                            double Pi,
                            const double *const restrict mu,
                            const double *const restrict rho,
                            const int *const restrict nthreads,
                            const int nthreads_len);

void ExactBackward_scalarMu(double *const restrict beta,
                            double *const restrict beta_g,
                            int *const restrict cur_beta_theta,
                            int *const restrict end_beta_theta,
                            const size_t beta_from_rec,
                            const size_t beta_t,
                            const size_t t,
                            const size_t from_rec,
                            const size_t to_rec,
                            const size_t L,
                            const size_t N,
                            double *const restrict Pi,
                            const double mu,
                            const double *const restrict rho,
                            const int *const restrict nthreads,
                            const int nthreads_len);

void ExactBackward(double *const restrict beta,
                   double *const restrict beta_g,
                   int *const restrict cur_beta_theta,
                   int *const restrict end_beta_theta,
                   const size_t beta_from_rec,
                   const size_t beta_t,
                   const size_t t,
                   const size_t from_rec,
                   const size_t to_rec,
                   const size_t L,
                   const size_t N,
                   double *const restrict Pi,
                   const double *const restrict mu,
                   const double *const restrict rho,
                   const int *const restrict nthreads,
                   const int nthreads_len);

void ExactBackward_speidel_scalarMu_scalarPi(double *const restrict beta,
                                             double *const restrict beta_g,
                                             int *const restrict cur_beta_theta,
                                             int *const restrict end_beta_theta,
                                             const size_t beta_from_rec,
                                             const size_t beta_t,
                                             const size_t t,
                                             const size_t from_rec,
                                             const size_t to_rec,
                                             const size_t L,
                                             const size_t N,
                                             double Pi,
                                             const double mu,
                                             const double *const restrict rho,
                                             const int *const restrict nthreads,
                                             const int nthreads_len);

void ExactBackward_speidel_scalarPi(double *const restrict beta,
                                    double *const restrict beta_g,
                                    int *const restrict cur_beta_theta,
                                    int *const restrict end_beta_theta,
                                    const size_t beta_from_rec,
                                    const size_t beta_t,
                                    const size_t t,
                                    const size_t from_rec,
                                    const size_t to_rec,
                                    const size_t L,
                                    const size_t N,
                                    double Pi,
                                    const double *const restrict mu,
                                    const double *const restrict rho,
                                    const int *const restrict nthreads,
                                    const int nthreads_len);

void ExactBackward_speidel_scalarMu(double *const restrict beta,
                                    double *const restrict beta_g,
                                    int *const restrict cur_beta_theta,
                                    int *const restrict end_beta_theta,
                                    const size_t beta_from_rec,
                                    const size_t beta_t,
                                    const size_t t,
                                    const size_t from_rec,
                                    const size_t to_rec,
                                    const size_t L,
                                    const size_t N,
                                    double *const restrict Pi,
                                    const double mu,
                                    const double *const restrict rho,
                                    const int *const restrict nthreads,
                                    const int nthreads_len);

void ExactBackward_speidel(double *const restrict beta,
                           double *const restrict beta_g,
                           int *const restrict cur_beta_theta,
                           int *const restrict end_beta_theta,
                           const size_t beta_from_rec,
                           const size_t beta_t,
                           const size_t t,
                           const size_t from_rec,
                           const size_t to_rec,
                           const size_t L,
                           const size_t N,
                           double *const restrict Pi,
                           const double *const restrict mu,
                           const double *const restrict rho,
                           const int *const restrict nthreads,
                           const int nthreads_len);

#endif
