# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ResetBackwardTable <- function(bck) {
    invisible(.Call('_kalis_ResetBackwardTable', PACKAGE = 'kalis', bck))
}

Backward_densePi_densemu_cpp <- function(bck, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Backward_densePi_densemu_cpp', PACKAGE = 'kalis', bck, t, Pi, mu, rho, nthreads))
}

Backward_scalarPi_densemu_cpp <- function(bck, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Backward_scalarPi_densemu_cpp', PACKAGE = 'kalis', bck, t, Pi, mu, rho, nthreads))
}

Backward_densePi_scalarmu_cpp <- function(bck, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Backward_densePi_scalarmu_cpp', PACKAGE = 'kalis', bck, t, Pi, mu, rho, nthreads))
}

Backward_scalarPi_scalarmu_cpp <- function(bck, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Backward_scalarPi_scalarmu_cpp', PACKAGE = 'kalis', bck, t, Pi, mu, rho, nthreads))
}

CacheHaplotypes_matrix_2 <- function(x, N, L, transpose) {
    .Call('_kalis_CacheHaplotypes_matrix_2', PACKAGE = 'kalis', x, N, L, transpose)
}

CacheHaplotypes_hdf5_2 <- function(nexthaps, N, L) {
    .Call('_kalis_CacheHaplotypes_hdf5_2', PACKAGE = 'kalis', nexthaps, N, L)
}

QueryCache2_ind <- function(idx) {
    .Call('_kalis_QueryCache2_ind', PACKAGE = 'kalis', idx)
}

QueryCache2_loc <- function(idx) {
    .Call('_kalis_QueryCache2_loc', PACKAGE = 'kalis', idx)
}

ClearHaplotypeCache2 <- function() {
    invisible(.Call('_kalis_ClearHaplotypeCache2', PACKAGE = 'kalis'))
}

ComputeStatus <- function() {
    invisible(.Call('_kalis_ComputeStatus', PACKAGE = 'kalis'))
}

Dedip_min <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_min', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_2nd_min <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_2nd_min', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_max <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_max', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_dom <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_dom', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_add <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_add', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_mean <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_mean', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip_all <- function(fwd, bck, s) {
    .Call('_kalis_Dedip_all', PACKAGE = 'kalis', fwd, bck, s)
}

Dedip2_min <- function(M) {
    .Call('_kalis_Dedip2_min', PACKAGE = 'kalis', M)
}

Dedip2_2nd_min <- function(M) {
    .Call('_kalis_Dedip2_2nd_min', PACKAGE = 'kalis', M)
}

Dedip2_dom <- function(M) {
    .Call('_kalis_Dedip2_dom', PACKAGE = 'kalis', M)
}

Dedip2_all <- function(M) {
    .Call('_kalis_Dedip2_all', PACKAGE = 'kalis', M)
}

ResetForwardTable <- function(fwd) {
    invisible(.Call('_kalis_ResetForwardTable', PACKAGE = 'kalis', fwd))
}

Forward_densePi_densemu_cpp <- function(fwd, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Forward_densePi_densemu_cpp', PACKAGE = 'kalis', fwd, t, Pi, mu, rho, nthreads))
}

Forward_scalarPi_densemu_cpp <- function(fwd, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Forward_scalarPi_densemu_cpp', PACKAGE = 'kalis', fwd, t, Pi, mu, rho, nthreads))
}

Forward_densePi_scalarmu_cpp <- function(fwd, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Forward_densePi_scalarmu_cpp', PACKAGE = 'kalis', fwd, t, Pi, mu, rho, nthreads))
}

Forward_scalarPi_scalarmu_cpp <- function(fwd, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Forward_scalarPi_scalarmu_cpp', PACKAGE = 'kalis', fwd, t, Pi, mu, rho, nthreads))
}

Forward1step_scalarPi_scalarmu_cpp <- function(fwd, t, Pi, mu, rho, nthreads) {
    invisible(.Call('_kalis_Forward1step_scalarPi_scalarmu_cpp', PACKAGE = 'kalis', fwd, t, Pi, mu, rho, nthreads))
}

ResetTable <- function(tbl) {
    invisible(.Call('_kalis_ResetTable', PACKAGE = 'kalis', tbl))
}

CopyForwardTable <- function(to, from) {
    invisible(.Call('_kalis_CopyForwardTable', PACKAGE = 'kalis', to, from))
}

