# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CacheAllSequences2 <- function(seqs, bufsize) {
    .Call('StatGen_CacheAllSequences2', PACKAGE = 'StatGen', seqs, bufsize)
}

QueryCache2 <- function(idx) {
    .Call('StatGen_QueryCache2', PACKAGE = 'StatGen', idx)
}

ClearSequenceCache2 <- function() {
    invisible(.Call('StatGen_ClearSequenceCache2', PACKAGE = 'StatGen'))
}

