# for(n in c(1,2,4,8,16,32,64)) {
#   sink(glue("src/unrolls/ExactForwardStencil_inner_unroll_{n}.h"))
#   unroll.forward.inner(n)
#   sink()
# }

unroll.forward.inner <- function(n) {
  n <- n-1

  # cat(glue("", .trim = FALSE), sep = "\n")
  # cat("\n")

  cat("/* File generated by R/unroll-forward-inner-loop.R */")
  cat("\n\n")

  cat(glue("double *alphaNow{0:n}    = alphaRow + donoroff*(32*KALIS_INTVEC_SIZE) + donor*(KALIS_DOUBLEVEC_SIZE*KALIS_UNROLL) + ({0:n}*KALIS_DOUBLEVEC_SIZE);", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("KALIS_DOUBLE _alpha{0:n} = KALIS_LOADU_DOUBLE(alphaNow{0:n});", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("KALIS_DOUBLE _pi{0:n}    = KALIS_LOADU_DOUBLE(PiRow + donoroff*(32*KALIS_INTVEC_SIZE) + donor*(KALIS_DOUBLEVEC_SIZE*KALIS_UNROLL) + ({0:n}*KALIS_DOUBLEVEC_SIZE));", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("_pi{0:n}                 = KALIS_MUL_DOUBLE(_pi{0:n}, _rho);", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("_alpha{0:n}              = KALIS_FMA_DOUBLE(_alpha{0:n}, _omRhoDivF, _pi{0:n}); // (Pi*rho + [(1-rho)/f] * alpha)", .trim = FALSE), sep = "\n")
  cat("\n")
  cat("#if !defined(KALIS_1STEP)\n")
  cat(glue("KALIS_DOUBLE _theta{0:n} = KALIS_SPREADBITSTO_DOUBLE((HA[(donor*(KALIS_DOUBLEVEC_SIZE*KALIS_UNROLL)+({0:n}*KALIS_DOUBLEVEC_SIZE))/32]) >> ((donor*(KALIS_DOUBLEVEC_SIZE*KALIS_UNROLL)+({0:n}*KALIS_DOUBLEVEC_SIZE))%32));", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("_theta{0:n}              = KALIS_FMA_DOUBLE(_theta{0:n}, _muTmp1, _muTmp2); // theta = H * (2*mu - 1) - mu + 1", .trim = FALSE), sep = "\n")
  cat("#else\n")
  cat(glue("KALIS_DOUBLE _theta{0:n} = KALIS_SET_DOUBLE(1.0);", .trim = FALSE), sep = "\n")
  cat("#endif\n")
  cat("\n")
  cat(glue("_alpha{0:n}              = KALIS_MUL_DOUBLE(_theta{0:n}, _alpha{0:n});", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("_f                   = KALIS_ADD_DOUBLE(_f, _alpha{0:n});", .trim = FALSE), sep = "\n")
  cat("\n")
  cat(glue("KALIS_STOREU_DOUBLE(alphaNow{0:n}, _alpha{0:n});", .trim = FALSE), sep = "\n")
}
